name: To execute the web test

on:
  workflow_dispatch:
  push:
      branches: ["master"]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
        - name: checkout the project
          uses: actions/checkout@v3

        - name: Install java
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

  About-Context:
    runs-on: ubuntu-latest
    steps:
        - name: Get the details from context
          run: |
            echo ${{github.actor}}
            echo ${{job.status}}
            echo ${{runner.os}}
            exit 1

  my-3rd-job:
    runs-on: ubuntu-latest
    if: ${{failure() }}
    needs: [About-Context]
    steps:
      - name: learning about job dependency
        run: echo '3d job executed'
        
  my-4th-job:
    runs-on: ubuntu-latest
    if: ${{always() }}
    needs: [About-Context]
    steps:
      - name: learning about job dependency
        run: echo '3d job executed'         
      
